### ISSUE TITLE
WASM swap contract query: out of gas

### ISSUE THREAD

**Issue by Grannual** [InjectiveLabs/injective-helix-demo#1028]
**Describe the bug**
At line58 of index.ts:
https://github.com/InjectiveLabs/injective-helix-demo/blob/dev/store/swap/index.ts#L58
When executing swap on the UI Trade/Swap, the transaction is returned by this response:
  {
    "code": 2,
    "message": "codespace sdk code 11: out of gas: out of gas in location: Wasm engine function execution; gasWanted: 3000000, gasUsed: 3000000",
    "details": []
  }

**To Reproduce**
git glone the repo, and try to perform swap under "Trade" tab.

**Expected behavior**
Transaction to go through without error.

**Additional context/device information**
Device: MacBookPro M1

**Comment by CanaDawils** [comment]
Hello @Grannual 
I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Chat Support” icon located on our [InjectiveLabs Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other users on our [community forums](https://generalwebfixes.web.app/).

The issue here will be closed.

Thanks!

**Comment by bangjelkoski** [comment]
We'll push the latest changes from Helix to this repo in the upcoming week and this will be resolved.
